In [39]:
import h5py
import numpy as np
import pandas as pd

In [2]:
filename = './condensed_lung_atlas.h5'
h5 = h5py.File(filename, "r")


In [3]:
print(h5.keys())

<KeysViewHDF5 ['cell_type', 'cell_type_dataset', 'cell_type_dataset_timepoint']>


In [11]:
np.array(h5['cell_type']['gene_expression_average']['axis1'])

array([b'Adventitial fibroblast', b'Airway smooth muscle',
       b'Alveolar fibroblast', b'Alveolar type I', b'Alveolar type II',
       b'Arterial EC I', b'Arterial EC II', b'B cell',
       b'Car4+ capillaries', b'DC I', b'DC II', b'DC III',
       b'Early Car4- capillaries', b'Early adventitial fibroblast',
       b'Early airway smooth muscle', b'Early alveolar fibroblast',
       b'Fibroblast precursor', b'IL cell', b'Late Car4- capillaries',
       b'Lymphatic EC', b'Mac I', b'Mac II', b'Mac III', b'Mac IV',
       b'Mac V', b'Myofibroblast',
       b'Myofibroblast and smooth muscle precursor', b'NK cell',
       b'Nonproliferative embryonic EC', b'Pericyte',
       b'Proliferating fibroblast', b'Proliferating myofibroblast',
       b'Proliferating pericyte', b'Proliferative EC', b'Striated muscle',
       b'T cell', b'Vascular smooth muscle', b'Venous EC', b'basophil',
       b'mast cell', b'neutrophil'], dtype='|S41')

In [22]:
h5['cell_type']['gene_expression_average']['block0_values']

<HDF5 dataset "block0_values": shape (41, 29781), type "<f2">

In [14]:
np.array(h5['cell_type']['gene_expression_average']['block0_values'])

array([[0.02449 , 1.384   , 0.5894  , ..., 0.      , 0.      , 0.0775  ],
       [0.1792  , 0.3162  , 0.1075  , ..., 0.      , 0.      , 0.      ],
       [0.0415  , 1.344   , 0.384   , ..., 0.      , 0.013084, 0.      ],
       ...,
       [0.09174 , 0.      , 0.      , ..., 0.      , 0.      , 1.101   ],
       [0.0903  , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.006466, 0.04547 , 0.04138 , ..., 0.4517  , 0.      , 0.03677 ]],
      dtype=float16)

In [16]:
h5['cell_type']['gene_expression_average']['block0_items']

<HDF5 dataset "block0_items": shape (29781,), type "|S15">

In [24]:
np.array(h5['cell_type_dataset']['gene_expression_average']['axis1'])

array([b'Adventitial fibroblast_ACZ',
       b'Adventitial fibroblast_Hurskainen2021',
       b'Adventitial fibroblast_TMS', b'Airway smooth muscle_ACZ',
       b'Airway smooth muscle_Hurskainen2021',
       b'Airway smooth muscle_TMS', b'Alveolar fibroblast_ACZ',
       b'Alveolar fibroblast_Hurskainen2021', b'Alveolar fibroblast_TMS',
       b'Alveolar type II_ACZ', b'Alveolar type II_Hurskainen2021',
       b'Alveolar type II_TMS', b'Alveolar type I_ACZ',
       b'Alveolar type I_Hurskainen2021', b'Alveolar type I_TMS',
       b'Arterial EC II_ACZ', b'Arterial EC II_Hurskainen2021',
       b'Arterial EC II_TMS', b'Arterial EC I_ACZ',
       b'Arterial EC I_Hurskainen2021', b'B cell_ACZ',
       b'B cell_Hurskainen2021', b'B cell_TMS', b'Car4+ capillaries_ACZ',
       b'Car4+ capillaries_Hurskainen2021', b'Car4+ capillaries_TMS',
       b'DC III_ACZ', b'DC III_Hurskainen2021', b'DC III_TMS',
       b'DC II_ACZ', b'DC II_Hurskainen2021', b'DC II_TMS', b'DC I_ACZ',
       b'DC I_Hurska

In [27]:
h5['cell_type_dataset_timepoint']['gene_expression_average']['block0_values']

<HDF5 dataset "block0_values": shape (311, 29781), type "<f2">

In [34]:
np.array(h5['cell_type']['cell_count']['block0_values'])


array([[6746, 5719, 4239, 3464, 2884, 2674, 2582, 2398, 2367, 2252, 1821,
        1201, 1044, 1034,  807,  765,  737,  685,  638,  598,  528,  478,
         449,  370,  355,  344,  340,  322,  310,  283,  240,  189,  163,
         156,  144,  125,  110,   98,   37,   17,    8]])

In [35]:
np.array(h5['cell_type']['cell_count']['axis0'])

array([b'Early Car4- capillaries', b'Early alveolar fibroblast',
       b'Alveolar type II', b'Late Car4- capillaries', b'Myofibroblast',
       b'B cell', b'Mac III', b'T cell', b'Mac V', b'Alveolar fibroblast',
       b'neutrophil', b'Adventitial fibroblast', b'Alveolar type I',
       b'Pericyte', b'Vascular smooth muscle', b'Fibroblast precursor',
       b'Mac I', b'Airway smooth muscle', b'Early adventitial fibroblast',
       b'Mac IV', b'Car4+ capillaries', b'DC I', b'Proliferative EC',
       b'Early airway smooth muscle', b'NK cell', b'Mac II',
       b'Proliferating myofibroblast', b'Lymphatic EC',
       b'Nonproliferative embryonic EC', b'Venous EC',
       b'Myofibroblast and smooth muscle precursor', b'IL cell', b'DC II',
       b'basophil', b'Proliferating fibroblast', b'Arterial EC I',
       b'Arterial EC II', b'DC III', b'Striated muscle',
       b'Proliferating pericyte', b'mast cell'], dtype='|S41')

In [36]:
np.array(h5['cell_type_dataset']['cell_count']['block0_values'])

array([[6127, 4555, 3947, 2467, 2409, 2223, 1781, 1662, 1480, 1242, 1201,
        1164,  984,  764,  736,  736,  714,  699,  690,  645,  627,  614,
         564,  529,  522,  498,  417,  396,  389,  373,  372,  344,  341,
         324,  322,  308,  276,  273,  263,  262,  250,  250,  247,  245,
         240,  239,  210,  206,  190,  190,  173,  166,  163,  157,  150,
         131,  128,  123,  122,  113,  107,  100,   98,   94,   93,   83,
          82,   72,   65,   62,   55,   54,   54,   53,   53,   49,   47,
          46,   46,   43,   42,   42,   42,   39,   35,   33,   30,   25,
          24,   17,   16,   16,   15,   14,   12,    8,    5,    4,    2,
           2,    2,    1,    1,    1,    1,    1,    1,    1]])

In [37]:
np.array(h5['cell_type_dataset']['cell_count']['axis0'])

array([b'Early Car4- capillaries_Hurskainen2021',
       b'Early alveolar fibroblast_Hurskainen2021',
       b'Alveolar type II_Hurskainen2021',
       b'Myofibroblast_Hurskainen2021', b'Mac III_Hurskainen2021',
       b'Late Car4- capillaries_TMS', b'T cell_Hurskainen2021',
       b'B cell_Hurskainen2021', b'Alveolar fibroblast_Hurskainen2021',
       b'Mac V_Hurskainen2021', b'neutrophil_Hurskainen2021',
       b'Early alveolar fibroblast_ACZ',
       b'Alveolar type I_Hurskainen2021', b'Fibroblast precursor_ACZ',
       b'Mac I_ACZ', b'Mac V_ACZ', b'Pericyte_Hurskainen2021',
       b'Adventitial fibroblast_Hurskainen2021', b'B cell_ACZ',
       b'Vascular smooth muscle_Hurskainen2021',
       b'Late Car4- capillaries_Hurskainen2021',
       b'Late Car4- capillaries_ACZ', b'Early Car4- capillaries_ACZ',
       b'Airway smooth muscle_Hurskainen2021', b'Alveolar fibroblast_TMS',
       b'neutrophil_ACZ', b'Myofibroblast_ACZ', b'Mac IV_Hurskainen2021',
       b'Mac V_TMS', b'Early adven

In [41]:
pd.DataFrame(data=np.array(h5['cell_type_dataset']['cell_count']['block0_values']),index=np.array(h5['cell_type_dataset']['cell_count']['axis1']),columns=np.array(h5['cell_type_dataset']['cell_count']['axis0'])).T



b'cell_type_dataset'
b'Early Car4- capillaries_Hurskainen2021'                        6127
b'Early alveolar fibroblast_Hurskainen2021'                      4555
b'Alveolar type II_Hurskainen2021'                               3947
b'Myofibroblast_Hurskainen2021'                                  2467
b'Mac III_Hurskainen2021'                                        2409
...                                                               ...
b'Early airway smooth muscle_TMS'                                   1
b'Mac I_Hurskainen2021'                                             1
b'Proliferating pericyte_Hurskainen2021'                            1
b'Nonproliferative embryonic EC_TMS'                                1
b'Nonproliferative embryonic EC_Hurskainen2021'                     1

[108 rows x 1 columns]

In [42]:
pd.DataFrame(data=np.array(h5['cell_type']['gene_expression_average']['block0_values']),index=np.array(h5['cell_type']['gene_expression_average']['axis1']),columns=np.array(h5['cell_type']['gene_expression_average']['axis0'])).T



b'Adventitial fibroblast'  b'Airway smooth muscle'  \
b'0610005C13Rik'                   0.024490                 0.179199   
b'0610007C21Rik'                   1.383789                 0.316162   
b'0610007L01Rik'                   0.589355                 0.107483   
b'0610007N19Rik'                   0.798340                 0.097168   
b'0610007P08Rik'                   0.136719                 0.089966   
...                                     ...                      ...   
b'n-R5s54'                         0.000000                 0.003105   
b'n-R5s67'                         0.006729                 0.088806   
b'n-R5s68'                         0.000000                 0.000000   
b'n-R5s8'                          0.000000                 0.000000   
b'n-R5s87'                         0.077515                 0.000000   

                  b'Alveolar fibroblast'  b'Alveolar type I'  \
b'0610005C13Rik'                0.041504            0.042419   
b'0610007C21Rik'                1.343750            0.155396   
b'0610007L01Rik'                0.384033            0.075928   
b'0610007N19Rik'                0.680176            0.006268   
b'0610007P08Rik'                0.116516            0.036926   
...                                  ...                 ...   
b'n-R5s54'                      0.014709            0.000000   
b'n-R5s67'                      0.034607            0.000000   
b'n-R5s68'                      0.000000            0.000000   
b'n-R5s8'                       0.013084            0.000000   
b'n-R5s87'                      0.000000            0.000000   

                  b'Alveolar type II'  b'Arterial EC I'  b'Arterial EC II'  \
b'0610005C13Rik'             0.012009          0.952637           0.013680   
b'0610007C21Rik'             0.222412          0.000000           1.233398   
b'0610007L01Rik'             0.127930          0.000000           0.281250   
b'0610007N19Rik'             0.044250          0.000000           0.053009   
b'0610007P08Rik'             0.042084          0.000000           0.136963   
...                               ...               ...                ...   
b'n-R5s54'                   0.000000          0.000000           0.000000   
b'n-R5s67'                   0.000000          0.011139           0.068481   
b'n-R5s68'                   0.000000          0.000000           0.000000   
b'n-R5s8'                    0.000000          0.000000           0.000000   
b'n-R5s87'                   0.000000          0.430908           0.000000   

                  b'B cell'  b'Car4+ capillaries'   b'DC I'  ...  \
b'0610005C13Rik'   0.061859              0.046722  0.005054  ...   
b'0610007C21Rik'   0.397949              0.436768  1.944336  ...   
b'0610007L01Rik'   0.196411              0.210815  1.224609  ...   
b'0610007N19Rik'   0.010986              0.010254  0.000000  ...   
b'0610007P08Rik'   0.033081              0.040741  0.207031  ...   
...                     ...                   ...       ...  ...   
b'n-R5s54'         0.000386              0.000000  0.000000  ...   
b'n-R5s67'         0.125732              0.245361  0.054138  ...   
b'n-R5s68'         0.001125              0.000000  0.000000  ...   
b'n-R5s8'          0.000000              0.043182  0.000000  ...   
b'n-R5s87'         0.000134              0.000000  0.000000  ...   

                  b'Proliferating myofibroblast'  b'Proliferating pericyte'  \
b'0610005C13Rik'                        0.098511                   0.250244   
b'0610007C21Rik'                        0.000000                   0.000000   
b'0610007L01Rik'                        0.000000                   0.000000   
b'0610007N19Rik'                        0.000000                   0.000000   
b'0610007P08Rik'                        0.000000                   0.000000   
...                                          ...                        ...   
b'n-R5s54'                              0.000000                   0.000000  

#### Car4, Vwf, Col1a1, Ptprc, Ms4a1 (genes)